# Generated by Django 5.0.6 on 2024-06-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beep', '0002_alter_event_creator_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendants',
            new_name='Attendant',
        ),
    ]
