# Generated by Django 5.0.6 on 2024-06-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beep', '0007_delete_attendant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beep.user', to_field='username'),
        ),
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendents_email', to='beep.user', to_field='email')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beep.event')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendents_name', to='beep.user', to_field='username')),
            ],
        ),
    ]
