# Generated by Django 5.0.6 on 2024-06-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beep', '0008_alter_event_creator_attendant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendant',
            new_name='Attendee',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='locatin',
            new_name='location',
        ),
    ]
